[package]
name = "ethlambda"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
ethlambda-p2p.workspace = true
ethlambda-types.workspace = true
ethlambda-rpc.workspace = true

tokio.workspace = true

tracing.workspace = true
tracing-subscriber = "0.3"

serde.workspace = true
ethereum-types.workspace = true
serde_json.workspace = true
clap.workspace = true
