[package]
name = "ethlambda-metrics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
prometheus.workspace = true
thiserror.workspace = true
